spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/huawei?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
servlet:
  encoding:
    charset: UTF-8
    enabled: true
    force: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.hospital.entity
server:
  port: 8080